### ISSUE TITLE
http proxy functionality does not work

### ISSUE THREAD

**Issue by Doodah65** [subhra74/snowflake#113]
**Describe the bug**
http proxy functionality does not work on RHELv7.7

**To Reproduce**
1. Start snowflake
2. configure a connection using a SOCKS proxy
3. click connect
4. connection times out

**Expected behavior**
Connection should open session to server over SOCKS

**Screenshots**
Output from snowflake from application startup, attempt SOCKS connection, close snowflake

Font loaded
value changed
treeNodesChanged
treeNodesChanged
Returned disposing
Selecting 1561422379
New wrapper session
java.awt.Dimension[width=64,height=35]
Row height: 35
Path: null
Rendering: null
Left drop down changed
Listing files now ...
Creating file system from thread pool-9-thread-1
Connecting to: MOP5_WAS1 on thread: pool-9-thread-1
New wrapper session
java.awt.Dimension[width=64,height=35]
Row height: 35
java.awt.Dimension[width=0,height=0]
java.awt.Dimension[width=0,height=0]
java.awt.Dimension[width=0,height=0]
java.awt.Dimension[width=0,height=0]
Setting text: /home/gb094947
Setting text done: /home/gb094947
java.awt.Dimension[width=131,height=19]
com.jcraft.jsch.JSchException: timeout: socket is not established
	at com.jcraft.jsch.Util.createSocket(Util.java:394)
	at com.jcraft.jsch.Session.connect(Session.java:215)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at snowflake.common.ssh.SshClient.connect(SshClient.java:123)
	at snowflake.common.ssh.files.SshFileSystem.connect(SshFileSystem.java:75)
	at snowflake.components.files.FileComponentHolder.getSshFileSystem(FileComponentHolder.java:325)
	at snowflake.components.files.browser.ssh.SshFileBrowserView.lambda$render$1(SshFileBrowserView.java:163)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Exception caught in sftp file browser
com.jcraft.jsch.JSchException: timeout: socket is not established
	at com.jcraft.jsch.Util.createSocket(Util.java:394)
	at com.jcraft.jsch.Session.connect(Session.java:215)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at snowflake.common.ssh.SshClient.connect(SshClient.java:123)
	at snowflake.common.ssh.files.SshFileSystem.connect(SshFileSystem.java:75)
	at snowflake.components.files.FileComponentHolder.getSshFileSystem(FileComponentHolder.java:325)
	at snowflake.components.files.browser.ssh.SshFileBrowserView.lambda$render$1(SshFileBrowserView.java:163)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
java.awt.Dimension[width=0,height=0]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by subhra74** [comment]
Yes, its a bug, also the fix is known, I need to create a new release to publish the fix
