### ISSUE TITLE
java.nio.file.InvalidPathException at snap package

### ISSUE THREAD

**Issue by brunojsilv** [subhra74/snowflake#130]
The local folder listing is not working because my home directory contains folders with accents created by the system for my location.
I ran the application through the terminal and received the following error line when starting a new connection:

java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/administrator/V??deos
	at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:145)
	at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
	at java.base/java.io.File.toPath(File.java:2292)
	at snowflake.common.local.files.LocalFileSystem.list(LocalFileSystem.java:59)
	at snowflake.components.files.browser.local.LocalFileBrowserView.lambda$new$1(LocalFileBrowserView.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

I moved the accented folders out of the home directory and the listing worked fine.

It appears to be some character encoding setting in Java.

![Captura de tela de 2020-06-01 13-43-34](https://user-images.githubusercontent.com/28793054/83431741-34c45180-a40e-11ea-824b-029e4156038b.png)

**Comment by angmac** [comment]
It seems that the snap version dosen't handle user locale settings ($LANG).

**Comment by ipesanz** [comment]
Same here, installed via snap
Same screenshoot (nothing is shown... just the foldersstructure, not any file in my pc)
Fedora 33

1st exception:
" /home/iperez/ Públic"

java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/iperez/P??blic
	at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:145)
	at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
	at java.base/java.io.File.toPath(File.java:2292)
	at snowflake.common.local.files.LocalFileSystem.list(LocalFileSystem.java:59)
	at snowflake.components.files.browser.local.LocalFileBrowserView.lambda$new$1(LocalFileBrowserView.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
