### ISSUE TITLE
broken symlink causing issues in directory display

### ISSUE THREAD

**Issue by gmcc** [subhra74/snowflake#14]
I have a broken symlink in my homedir. It is preventing snowflake from loading the directory in the Local Files viewer.

[gmcc@darkstar ~]$ ln -s /tmp/does-not-exist broken
[gmcc@darkstar ~]$ ls -l broken 
lrwxrwxrwx. 1 gmcc gmcc 19 Jan 29 23:43 broken -> /tmp/does-not-exist
[gmcc@darkstar ~]$ ls -l /tmp/does-not-exist
ls: cannot access '/tmp/does-not-exist': No such file or directory
[gmcc@darkstar ~]$ 

When i browse to my homedir on using snowflake it will not load.
I see this error.
Mouse click on table
java.nio.file.NoSuchFileException: /home/gmcc/broken
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(Unknown Source)
	at java.base/java.nio.file.Files.readAttributes(Unknown Source)
	at snowflake.common.local.files.LocalFileSystem.list(LocalFileSystem.java:60)
	at snowflake.components.files.browser.local.LocalFileBrowserView.lambda$render$3(LocalFileBrowserView.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

If i remove the broken file I can view the directory.

**Comment by gmcc** [comment]
i would expect the directory to load, even better if the broken file was bold red.

**Comment by subhra74** [comment]
Thanks for reporting this issue, will be fixed on next release.

**Comment by subhra74** [comment]
fixed in 1.0.4
