### ISSUE TITLE
Exception in thread "main" java.lang.Error: Cannot load javax.swing.plaf.metal.MetalLookAndFeel

### ISSUE THREAD

**Issue by hdward9** [subhra74/snowflake#200]
**Describe the bug**
Error when opening

Exception in thread "main" java.lang.Error: Cannot load javax.swing.plaf.metal.MetalLookAndFeel
	at java.desktop/javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1406)
	at java.desktop/javax.swing.UIManager.initialize(UIManager.java:1517)
	at java.desktop/javax.swing.UIManager.maybeInitialize(UIManager.java:1483)
	at java.desktop/javax.swing.UIManager.getDefaults(UIManager.java:709)
	at java.desktop/javax.swing.UIManager.getColor(UIManager.java:751)
	at java.desktop/javax.swing.plaf.nimbus.DerivedColor.rederiveColor(DerivedColor.java:81)
	at java.desktop/javax.swing.plaf.nimbus.NimbusDefaults.getDerivedColor(NimbusDefaults.java:1640)
	at java.desktop/javax.swing.plaf.nimbus.NimbusDefaults.addColor(NimbusDefaults.java:1597)
	at java.desktop/javax.swing.plaf.nimbus.NimbusDefaults.addColor(NimbusDefaults.java:1591)
	at java.desktop/javax.swing.plaf.nimbus.NimbusDefaults.initializeDefaults(NimbusDefaults.java:249)
	at java.desktop/javax.swing.plaf.nimbus.NimbusLookAndFeel.getDefaults(NimbusLookAndFeel.java:138)
	at snowflake.App.main(App.java:68)

**Desktop (please complete the following information):**
 - OS: [ Ubuntu 21.10 ]
 - JDK Version [OpenJDK 11 OpenJ9 jvm]

**Comment by devlinx9** [comment]
Hello, you could try a fork of this software: https://github.com/devlinx9/muon-ssh
