### ISSUE TITLE
Invalid SSH key.

### ISSUE THREAD

**Issue by ComputerTech312** [subhra74/snowflake#233]
When i use an ssh key on for my server(and it works fine with openssh) it gives me the following error: "Unable to connect to server X at X, do you want to retry?"

I launched snowflake from the terminal and i'm getting the following error: 
`colby@laptop:~$ snowflake
Font loaded
value changed
treeNodesChanged
treeNodesChanged
Returned disposing
Selecting 1182252021
New wrapper session
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
New wrapper session
com.jcraft.jsch.JSchException: invalid privatekey: [B@159258dd
	at com.jcraft.jsch.KeyPair.load(KeyPair.java:664)
	at com.jcraft.jsch.KeyPair.load(KeyPair.java:561)
	at com.jcraft.jsch.IdentityFile.newInstance(IdentityFile.java:40)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:407)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:367)
	at snowflake.common.ssh.SshClient.connect(SshClient.java:66)
	at snowflake.components.terminal.ssh.SshTtyConnector.init(SshTtyConnector.java:40)
	at com.jediterm.terminal.ui.JediTermWidget$EmulatorTask.run(JediTermWidget.java:358)
	at java.base/java.lang.Thread.run(Thread.java:829)
Terminal wrapper disconnecting
java.lang.NullPointerException
	at snowflake.common.ssh.SshClient.disconnect(SshClient.java:140)
	at snowflake.components.terminal.ssh.SshTtyConnector.close(SshTtyConnector.java:84)
	at com.jediterm.terminal.ui.JediTermWidget$EmulatorTask.run(JediTermWidget.java:367)
	at java.base/java.lang.Thread.run(Thread.java:829)
Disconnected
` Which makes no sense, since the privatekey is valid.

**Comment by fmakrid** [comment]
Same issue, even though i can connect via zsh without issue, when i try with Snowflake i get "Unable to connect to server X at X, do you want to retry?" also.
