### ISSUE TITLE
Seems logging is borked

### ISSUE THREAD

**Issue by cstamas** [subhra74/snowflake#31]
While running the app, on console I got these lines (and they tell all):

```
log4j:WARN No appenders could be found for logger (com.jediterm.terminal.emulator.JediEmulator).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```
Also, the log could be properly formatted, with level, timestamp, etc, as currently it looks like a flow of printlns

**Comment by Bass850** [comment]
BTW after running Snowflake from CLI and trying to connect to the NAS i noticed these errors:

com.jcraft.jsch.JSchException: failed to send channel request
	at com.jcraft.jsch.Request.write(Request.java:65)
	at com.jcraft.jsch.RequestSftp.request(RequestSftp.java:47)
	at com.jcraft.jsch.ChannelSftp.start(ChannelSftp.java:237)
	at com.jcraft.jsch.Channel.connect(Channel.java:152)
	at com.jcraft.jsch.Channel.connect(Channel.java:145)
	at snowflake.common.ssh.SshClient.getSftpChannel(SshClient.java:113)
	at snowflake.common.ssh.files.SshFileSystem.connect(SshFileSystem.java:80)
	at snowflake.components.files.FileComponentHolder.getSshFileSystem(FileComponentHolder.java:306)
	at snowflake.components.files.browser.ssh.SshFileBrowserView.lambda$render$1(SshFileBrowserView.java:163)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Exception caught in sftp file browser
com.jcraft.jsch.JSchException: failed to send channel request
	at com.jcraft.jsch.Request.write(Request.java:65)
	at com.jcraft.jsch.RequestSftp.request(RequestSftp.java:47)
	at com.jcraft.jsch.ChannelSftp.start(ChannelSftp.java:237)
	at com.jcraft.jsch.Channel.connect(Channel.java:152)
	at com.jcraft.jsch.Channel.connect(Channel.java:145)
	at snowflake.common.ssh.SshClient.getSftpChannel(SshClient.java:113)
	at snowflake.common.ssh.files.SshFileSystem.connect(SshFileSystem.java:80)
	at snowflake.components.files.FileComponentHolder.getSshFileSystem(FileComponentHolder.java:306)
	at snowflake.components.files.browser.ssh.SshFileBrowserView.lambda$render$1(SshFileBrowserView.java:163)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
log4j:WARN No appenders could be found for logger (com.jediterm.terminal.emulator.JediEmulator).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.


It might seem that synology is not allowing file connection?
